/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controllers.InitialData;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DeMotorModel;
import access.BarcoDAO;
import access.DeMotorDAO;

/**
 *
 * @author User
 */
public class EliminarInfoDeMotor extends javax.swing.JDialog {

  /**
   * Creates new form EliminarInfoDeMotor
   *
   * @param mainWindow
   * @param modal
   */
  public EliminarInfoDeMotor(MainWindow mainWindow, boolean modal) {
    super(mainWindow, modal);
    initComponents();
    this.setLocationRelativeTo(null);
    FieldMarca.setEnabled(false);
    FieldAutonomia.setEnabled(false);
    FieldCantidadmotores.setEnabled(false);
    FieldPropietario.setEnabled(false);

    try {
      CargarComboBox();
    } catch (ParseException ex) {
      Logger.getLogger(AgregarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException | IOException | org.json.simple.parser.ParseException ex) {
      Logger.getLogger(EliminarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
    }

    actualizarInfoCasillas();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloEliminar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelinfoElim = new javax.swing.JLabel();
        labelRegistroElim = new javax.swing.JLabel();
        desplegableRegistros = new javax.swing.JComboBox<>();
        Eliminar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        labelRegistroElim1 = new javax.swing.JLabel();
        FieldMarca = new javax.swing.JTextField();
        labelRegistroElim2 = new javax.swing.JLabel();
        FieldAutonomia = new javax.swing.JTextField();
        labelRegistroElim3 = new javax.swing.JLabel();
        FieldCantidadmotores = new javax.swing.JTextField();
        labelRegistroElim4 = new javax.swing.JLabel();
        FieldPropietario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar - Barco de motor");

        labelTituloEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTituloEliminar.setText("Eliminar - Barco de motor");

        labelinfoElim.setText("Seleccione el registro del barco");

        labelRegistroElim.setText("Registro:");

        desplegableRegistros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Eliminar.setText("Eliminar información");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        labelRegistroElim1.setText("Marca:");

        labelRegistroElim2.setText("Autonomía (horas):");

        labelRegistroElim3.setText("Cantidad de Motores:");

        labelRegistroElim4.setText("Propietario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTituloEliminar)
                                    .addComponent(labelinfoElim))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Eliminar)
                        .addGap(28, 28, 28)
                        .addComponent(Cancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelRegistroElim2)
                                        .addGap(178, 178, 178))
                                    .addComponent(labelRegistroElim1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(1, 1, 1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelRegistroElim3)
                                    .addComponent(labelRegistroElim4)
                                    .addComponent(labelRegistroElim))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(desplegableRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FieldPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FieldCantidadmotores, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FieldAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelinfoElim)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRegistroElim)
                    .addComponent(desplegableRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRegistroElim1)
                    .addComponent(FieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRegistroElim2)
                    .addComponent(FieldAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRegistroElim3)
                    .addComponent(FieldCantidadmotores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRegistroElim4)
                    .addComponent(FieldPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(Cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void CargarComboBox() throws SQLException, IOException, ParseException, org.json.simple.parser.ParseException {
    desplegableRegistros.removeAllItems();
    ArrayList<String> lista = InitialData.CargarRegistrosDeMotor();
    for (int i = 0; i < lista.size(); i++) {
      desplegableRegistros.addItem(lista.get(i));
    }
  }

  private void actualizarInfoCasillas() {
    desplegableRegistros.addActionListener((ActionEvent e) -> {
      try {
        String registroSel = desplegableRegistros.getSelectedItem().toString();
        DeMotorModel datosDeMotorSinRegistro = InitialData.cargarDatosDeMotorSinRegistro(registroSel);

        FieldMarca.setText(datosDeMotorSinRegistro.getMarca());
        FieldCantidadmotores.setText(datosDeMotorSinRegistro.getCantidadMotores().toString());
        FieldAutonomia.setText(datosDeMotorSinRegistro.getAutonomiaHoras().toString());

        FieldPropietario.setText(datosDeMotorSinRegistro.getPropietarioNombre());

      } catch (IOException | java.text.ParseException | SQLException ex) {
        Logger.getLogger(EditarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
      }
    });
  }

  private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

    int dialogButton = JOptionPane.showConfirmDialog(null, "¿Está seguro que quiere eliminar los datos de ese registro?", "ATENCIÓN", JOptionPane.YES_NO_OPTION);
    if (dialogButton == JOptionPane.YES_OPTION) {

      try {
        String registro = desplegableRegistros.getSelectedItem().toString();

        DeMotorDAO demotor = new DeMotorDAO();
        demotor.eliminarBarco(registro);

        BarcoDAO barco = new BarcoDAO();
        barco.eliminarBarco(registro);

      } catch (IOException | org.json.simple.parser.ParseException | ParseException ex) {
        Logger.getLogger(EliminarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
      }
      JOptionPane.showMessageDialog(null, "La entrada se eliminó exitosamente");
      dispose();
    }

  }//GEN-LAST:event_EliminarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
      dispose();
    }//GEN-LAST:event_CancelarActionPerformed

  /**
   * @param args the command line arguments
   */
  /*public static void main(String args[]) {
    /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
 /* try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(EliminarInfoDeMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(EliminarInfoDeMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(EliminarInfoDeMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(EliminarInfoDeMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }*/
  //</editor-fold>

  /* Create and display the form */
 /* java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new EliminarInfoDeMotor().setVisible(true);
      }
    });
  }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField FieldAutonomia;
    private javax.swing.JTextField FieldCantidadmotores;
    private javax.swing.JTextField FieldMarca;
    private javax.swing.JTextField FieldPropietario;
    private javax.swing.JComboBox<String> desplegableRegistros;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelRegistroElim;
    private javax.swing.JLabel labelRegistroElim1;
    private javax.swing.JLabel labelRegistroElim2;
    private javax.swing.JLabel labelRegistroElim3;
    private javax.swing.JLabel labelRegistroElim4;
    private javax.swing.JLabel labelTituloEliminar;
    private javax.swing.JLabel labelinfoElim;
    // End of variables declaration//GEN-END:variables
}
