/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import access.BarcoDAO;
import access.DeMotorDAO;
import controllers.ClickEvent;
import controllers.InitialData;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DeMotorModel;

/**
 *
 * @author lipasofra y camilo
 */
public class AgregarInfoDeMotor extends javax.swing.JDialog {

  /**
   * Creates new form AgregarInfoDeMotor
   *
   * @param mainWindow
   * @param modal
   * @throws java.sql.SQLException
   * @throws java.io.IOException
   * @throws org.json.simple.parser.ParseException
   */
  public AgregarInfoDeMotor(MainWindow mainWindow, boolean modal) throws SQLException, IOException, org.json.simple.parser.ParseException {
    super(mainWindow, modal);
    initComponents();
    FieldIdpropietario.setEnabled(false);
    this.setLocationRelativeTo(null);

    try {
      CargarComboBox();
    } catch (ParseException ex) {
      Logger.getLogger(AgregarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
    }
    activarcasilla();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    LabelComplete = new javax.swing.JLabel();
    LabelRegistro = new javax.swing.JLabel();
    FieldRegistro = new javax.swing.JTextField();
    LabelMarca = new javax.swing.JLabel();
    FieldMarca = new javax.swing.JTextField();
    LabelCantidadmotores = new javax.swing.JLabel();
    FieldCantidadmotores = new javax.swing.JTextField();
    LabelNombrepropietario = new javax.swing.JLabel();
    FieldAutonomia = new javax.swing.JTextField();
    BotonCancelar = new javax.swing.JButton();
    LabelTitulo = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    DesplegablePropietarios = new javax.swing.JComboBox<>();
    LabelAutonomia = new javax.swing.JLabel();
    LabelIdpropietario = new javax.swing.JLabel();
    FieldIdpropietario = new javax.swing.JTextField();
    BotonAgregar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Agregar info barcos de motor");
    setResizable(false);

    LabelComplete.setText("Complete la siguiente información");

    LabelRegistro.setText("Registro: ");

    LabelMarca.setText("Marca:");

    LabelCantidadmotores.setText("Cantidad de motores:");

    LabelNombrepropietario.setText("Nombre del Propietario");

    BotonCancelar.setText("Cancelar");
    BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BotonCancelarActionPerformed(evt);
      }
    });

    LabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    LabelTitulo.setText("Agregar - Barco de motor");

    DesplegablePropietarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    LabelAutonomia.setText("Autonomía en horas:");

    LabelIdpropietario.setText("Id Propietario");

    BotonAgregar.setText("Agregar información");
    BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BotonAgregarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jSeparator1)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(LabelTitulo)
              .addComponent(LabelComplete)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(LabelCantidadmotores)
                  .addComponent(LabelMarca)
                  .addComponent(LabelRegistro))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(FieldCantidadmotores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                  .addComponent(FieldMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(FieldRegistro, javax.swing.GroupLayout.Alignment.TRAILING)))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(LabelNombrepropietario)
                  .addComponent(LabelAutonomia)
                  .addComponent(LabelIdpropietario))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(FieldIdpropietario)
                  .addComponent(DesplegablePropietarios, 0, 142, Short.MAX_VALUE)
                  .addComponent(FieldAutonomia))))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addComponent(BotonAgregar)
        .addGap(29, 29, 29)
        .addComponent(BotonCancelar)
        .addContainerGap(60, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(LabelTitulo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(LabelComplete)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(LabelRegistro)
          .addComponent(FieldRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(11, 11, 11)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(LabelMarca)
          .addComponent(FieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(14, 14, 14)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(LabelCantidadmotores)
          .addComponent(FieldCantidadmotores, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(14, 14, 14)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(FieldAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(LabelAutonomia))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(DesplegablePropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(LabelNombrepropietario))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(LabelIdpropietario)
          .addComponent(FieldIdpropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(BotonAgregar)
          .addComponent(BotonCancelar))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void CargarComboBox() throws SQLException, IOException, ParseException, org.json.simple.parser.ParseException {
    DesplegablePropietarios.removeAllItems();
    ArrayList<String> lista = InitialData.CargarPropietarios();
    for (int i = 0; i < lista.size(); i++) {
      DesplegablePropietarios.addItem(lista.get(i));
    }
  }

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
      dispose();
    }//GEN-LAST:event_BotonCancelarActionPerformed


    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed

      try {
        String registro = (String) this.FieldRegistro.getText();
        String marca = (String) this.FieldMarca.getText();
        int cantidadMotores = Integer.parseInt((String) this.FieldCantidadmotores.getText());
        int autonomia = Integer.parseInt((String) this.FieldAutonomia.getText());
        Long propietarioId = Long.parseLong((String) this.FieldIdpropietario.getText());

        DeMotorModel nuevomotor = new DeMotorModel(registro, propietarioId, marca, cantidadMotores, autonomia);
        BarcoDAO barcoDAO = new BarcoDAO();
        barcoDAO.agregarBarco(nuevomotor);

        DeMotorDAO demotorDao = new DeMotorDAO();
        demotorDao.agregarBarco(nuevomotor);

        JOptionPane.showMessageDialog(null, "Información agregada exitosamente");
        
//        new ClickEvent().actualizarTablaInfo();

        dispose();

      } catch (NumberFormatException ex) {
        System.out.println(ex);
        JOptionPane.showMessageDialog(null, "Por favor ingrese solo números enteros para Cantidad de Motores y Autonomía");
      } catch (ParseException ex) {
        Logger.getLogger(AgregarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_BotonAgregarActionPerformed

  public void activarcasilla() {
    DesplegablePropietarios.addActionListener((ActionEvent e) -> {
      try {
        String propietarioNombre = DesplegablePropietarios.getSelectedItem().toString();
        String propietarioId1 = InitialData.CargarIdPropietario(propietarioNombre);
        FieldIdpropietario.setText(propietarioId1);
      } catch (ParseException ex) {
        Logger.getLogger(AgregarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
      }
    });
  }

  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Windows".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(AgregarInfoDeMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(AgregarInfoDeMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(AgregarInfoDeMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(AgregarInfoDeMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
//    //</editor-fold>
//
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        try {
//          new AgregarInfoDeMotor().setVisible(true);
//
//        } catch (SQLException | IOException | org.json.simple.parser.ParseException ex) {
//          Logger.getLogger(AgregarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
//        }
//      }
//    });
//  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton BotonAgregar;
  private javax.swing.JButton BotonCancelar;
  private javax.swing.JComboBox<String> DesplegablePropietarios;
  private javax.swing.JTextField FieldAutonomia;
  private javax.swing.JTextField FieldCantidadmotores;
  private javax.swing.JTextField FieldIdpropietario;
  private javax.swing.JTextField FieldMarca;
  private javax.swing.JTextField FieldRegistro;
  private javax.swing.JLabel LabelAutonomia;
  private javax.swing.JLabel LabelCantidadmotores;
  private javax.swing.JLabel LabelComplete;
  private javax.swing.JLabel LabelIdpropietario;
  private javax.swing.JLabel LabelMarca;
  private javax.swing.JLabel LabelNombrepropietario;
  private javax.swing.JLabel LabelRegistro;
  private javax.swing.JLabel LabelTitulo;
  private javax.swing.JSeparator jSeparator1;
  // End of variables declaration//GEN-END:variables

  /**
   * @param propietarios
   */
  /**
   * @return the DesplegablePropietarios
   */
  public javax.swing.JComboBox<String> getDesplegablePropietarios() {
    return DesplegablePropietarios;
  }
}
