/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import access.BarcoDAO;
import access.DeMotorDAO;
import controllers.InitialData;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DeMotorModel;
import org.json.simple.parser.ParseException;

/**
 *
 * @author lipasofra y camilo
 */
public class EditarInfoDeMotor extends javax.swing.JDialog {

  /**
   * Creates new form EditarInfoDeMotor
   *
   * @param mainWindow
   * @param modal
   * @throws java.sql.SQLException
   * @throws java.io.IOException
   * @throws org.json.simple.parser.ParseException
   * @throws java.text.ParseException
   */
  public EditarInfoDeMotor(MainWindow mainWindow, boolean modal) throws SQLException, IOException, ParseException, java.text.ParseException {
    super(mainWindow, modal);
    initComponents();
    this.setLocationRelativeTo(null);

    cargarComboBox();
    actualizarInfoCasillas();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelTituloEditar = new javax.swing.JLabel();
    labelInfo = new javax.swing.JLabel();
    labelRegistro = new javax.swing.JLabel();
    listaRegistro = new javax.swing.JComboBox<>();
    jSeparator1 = new javax.swing.JSeparator();
    panelEditarInfo = new javax.swing.JPanel();
    labelMarcaEdit = new javax.swing.JLabel();
    labelCantMotEdit = new javax.swing.JLabel();
    labelAutonomiaEdit = new javax.swing.JLabel();
    cajaAutonomiaEdit = new javax.swing.JTextField();
    cajaCantMotEdit = new javax.swing.JTextField();
    cajaMarcaEdit = new javax.swing.JTextField();
    labelPropietarioEdit = new javax.swing.JLabel();
    listaPropietariosEdit = new javax.swing.JComboBox<>();
    labelIDPropEdit = new javax.swing.JLabel();
    cajaIDPropietarioEdit = new javax.swing.JTextField();
    btnEditarMot = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Editar - Barco de Motor");

    labelTituloEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    labelTituloEditar.setText("Editar - Barco de motor");

    labelInfo.setText("Seleccione el registro del barco que quiere editar");

    labelRegistro.setText("Registro:");

    panelEditarInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Edite la información aquí"));

    labelMarcaEdit.setText("Marca:");

    labelCantMotEdit.setText("Cantidad de motores:");

    labelAutonomiaEdit.setText("Autonomia en horas:");

    labelPropietarioEdit.setText("Propietario:");

    listaPropietariosEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    labelIDPropEdit.setText("ID propietario:");

    cajaIDPropietarioEdit.setEditable(false);

    javax.swing.GroupLayout panelEditarInfoLayout = new javax.swing.GroupLayout(panelEditarInfo);
    panelEditarInfo.setLayout(panelEditarInfoLayout);
    panelEditarInfoLayout.setHorizontalGroup(
      panelEditarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEditarInfoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelEditarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(panelEditarInfoLayout.createSequentialGroup()
            .addGroup(panelEditarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelCantMotEdit)
              .addComponent(labelMarcaEdit))
            .addGap(18, 18, 18)
            .addGroup(panelEditarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(cajaCantMotEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(cajaMarcaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(panelEditarInfoLayout.createSequentialGroup()
            .addGroup(panelEditarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelAutonomiaEdit)
              .addComponent(labelPropietarioEdit)
              .addComponent(labelIDPropEdit))
            .addGap(18, 18, 18)
            .addGroup(panelEditarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(listaPropietariosEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(cajaAutonomiaEdit)
              .addComponent(cajaIDPropietarioEdit))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelEditarInfoLayout.setVerticalGroup(
      panelEditarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEditarInfoLayout.createSequentialGroup()
        .addGroup(panelEditarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelMarcaEdit)
          .addComponent(cajaMarcaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelEditarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelCantMotEdit)
          .addComponent(cajaCantMotEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelEditarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelAutonomiaEdit)
          .addComponent(cajaAutonomiaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(9, 9, 9)
        .addGroup(panelEditarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelPropietarioEdit)
          .addComponent(listaPropietariosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(14, 14, 14)
        .addGroup(panelEditarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cajaIDPropietarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelIDPropEdit))
        .addContainerGap(15, Short.MAX_VALUE))
    );

    btnEditarMot.setText("Editar información");
    btnEditarMot.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditarMotActionPerformed(evt);
      }
    });

    btnCancelar.setText("Cancelar");
    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelEditarInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jSeparator1)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelTituloEditar)
              .addComponent(labelInfo)
              .addGroup(layout.createSequentialGroup()
                .addComponent(labelRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btnEditarMot)
            .addGap(18, 18, 18)
            .addComponent(btnCancelar)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelTituloEditar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(listaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelRegistro))
        .addGap(18, 18, 18)
        .addComponent(panelEditarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnCancelar)
          .addComponent(btnEditarMot))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnEditarMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMotActionPerformed
    
    int dialogButton = JOptionPane.showConfirmDialog(null, "¿Está seguro que quiere editar los datos de ese registro?", "ATENCIÓN", JOptionPane.YES_NO_OPTION);
    if (dialogButton == JOptionPane.YES_OPTION) {
    
    try {
      String registro = listaRegistro.getSelectedItem().toString();
      String marca = cajaMarcaEdit.getText();
      Integer cantidadMotores = Integer.parseInt(cajaCantMotEdit.getText());
      Integer autonomia = Integer.parseInt(cajaAutonomiaEdit.getText());
      Long IDPropietario = Long.parseLong(cajaIDPropietarioEdit.getText());

      DeMotorModel deMotorEditado = new DeMotorModel(registro, IDPropietario, marca, cantidadMotores, autonomia);
      BarcoDAO barcoDAO = new BarcoDAO();
      barcoDAO.editarBarco(deMotorEditado);

      DeMotorDAO demotorDao = new DeMotorDAO();
      demotorDao.editarBarcoDeMotor(deMotorEditado);

      JOptionPane.showMessageDialog(null, "Información editada exitosamente");

      dispose();

    } catch (NumberFormatException ex) {
      System.out.println(ex);
      JOptionPane.showMessageDialog(null, "Por favor ingrese solo números enteros para Cantidad de Motores y Autonomía");
    } catch (java.text.ParseException ex) {
      Logger.getLogger(EditarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
      Logger.getLogger(EditarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
      Logger.getLogger(EditarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
  }//GEN-LAST:event_btnEditarMotActionPerformed

  private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    dispose();
  }//GEN-LAST:event_btnCancelarActionPerformed

  private void cargarComboBox() throws IOException, java.text.ParseException, SQLException, ParseException {
    listaRegistro.removeAllItems();
    ArrayList<String> listaReg = InitialData.CargarRegistrosDeMotor();
    for (int i = 0; i < listaReg.size(); i++) {
      listaRegistro.addItem(listaReg.get(i));
    }

    listaPropietariosEdit.removeAllItems();
    ArrayList<String> listaPropietarios = InitialData.CargarPropietarios();
    for (int i = 0; i < listaPropietarios.size(); i++) {
      listaPropietariosEdit.addItem(listaPropietarios.get(i));
    }
  }

  private void actualizarInfoCasillas() {
    listaRegistro.addActionListener((ActionEvent e) -> {
      try {
        String registroSel = listaRegistro.getSelectedItem().toString();
        DeMotorModel datosDeMotorSinRegistro = InitialData.cargarDatosDeMotorSinRegistro(registroSel);

        cajaMarcaEdit.setText(datosDeMotorSinRegistro.getMarca());
        cajaCantMotEdit.setText(datosDeMotorSinRegistro.getCantidadMotores().toString());
        cajaAutonomiaEdit.setText(datosDeMotorSinRegistro.getAutonomiaHoras().toString());

        listaPropietariosEdit.setSelectedItem(datosDeMotorSinRegistro.getPropietarioNombre());

      } catch (IOException | java.text.ParseException | SQLException ex) {
        Logger.getLogger(EditarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
      }
    });

    listaPropietariosEdit.addActionListener((ActionEvent e) -> {
      try {
        cajaIDPropietarioEdit.setText(InitialData.CargarIdPropietario(listaPropietariosEdit.getSelectedItem().toString()));
      } catch (java.text.ParseException ex) {
        Logger.getLogger(EditarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
      }
    });
  }

  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Windows".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(EditarInfoDeMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(EditarInfoDeMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(EditarInfoDeMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(EditarInfoDeMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
//    //</editor-fold>
//
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        try {
//          new EditarInfoDeMotor().setVisible(true);
//        } catch (SQLException ex) {
//          Logger.getLogger(EditarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//          Logger.getLogger(EditarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ParseException ex) {
//          Logger.getLogger(EditarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (java.text.ParseException ex) {
//          Logger.getLogger(EditarInfoDeMotor.class.getName()).log(Level.SEVERE, null, ex);
//        }
//      }
//    });
//  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancelar;
  private javax.swing.JButton btnEditarMot;
  private javax.swing.JTextField cajaAutonomiaEdit;
  private javax.swing.JTextField cajaCantMotEdit;
  private javax.swing.JTextField cajaIDPropietarioEdit;
  private javax.swing.JTextField cajaMarcaEdit;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JLabel labelAutonomiaEdit;
  private javax.swing.JLabel labelCantMotEdit;
  private javax.swing.JLabel labelIDPropEdit;
  private javax.swing.JLabel labelInfo;
  private javax.swing.JLabel labelMarcaEdit;
  private javax.swing.JLabel labelPropietarioEdit;
  private javax.swing.JLabel labelRegistro;
  private javax.swing.JLabel labelTituloEditar;
  private javax.swing.JComboBox<String> listaPropietariosEdit;
  private javax.swing.JComboBox<String> listaRegistro;
  private javax.swing.JPanel panelEditarInfo;
  // End of variables declaration//GEN-END:variables
}
